Hangman
maksimfil/NIX_java_education_-_-. pull request #5
Opened 2021-11-18 10:16 UTC by maksimfil

Hangman Finished Project

2021-11-18 22:25 UTC, maxsomochkin requested changes

2021-11-18 22:25 UTC, maxsomochkin commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +    public void choice_word() {
По конвенции джава названия методов и переменных public void choiceWord(). Исправь все методы и переменные

2021-11-18 22:25 UTC, maxsomochkin commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +    public int check_count_include(String user_letter,String correct_word){
Если метод используешь только внутри класса делай его приватным

2021-11-18 22:25 UTC, maxsomochkin commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +                System.exit(0);
Не используй System.exit(0); для выхода из программы. Пиши так чтобы программа или метод сама завершалась

2021-11-18 22:25 UTC, maxsomochkin commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +        while (true) {
Помести цикл внутрь метода в в классе Hangman. Или другой класс. Привыкай использовать main только для работы с обьектами.

2021-11-18 22:25 UTC, maxsomochkin commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +                do {
логически завершенные блоки можно выносить в методы

2021-11-20 10:03 UTC, maxsomochkin requested changes
Почему не поправил змечания?

2021-11-20 10:03 UTC, maxsomochkin commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +    private void replacingLetters(String player_letter) {
String userLetter - Правильное название переменных

2021-11-21 23:31 UTC, asrubel commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +            int indexFirst = this.correctWord.indexOf(playerLetter);
старайся код разбивать на читабельные блоки

2021-11-21 23:31 UTC, asrubel commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +        for (int i =0;i<this.getCorrectWord().length();i++){
Пробелов не хватает

2021-11-21 23:32 UTC, asrubel commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +        while (true) {
ОЧень много вложенных условий и еще цикл внутри - разбивай на методы

2021-11-25 23:06 UTC, asrubel commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +    private String field;
Добавь конструктор и там проинициализируй свои свойства, они у тебя сетятся по ходу работы - это чревато ошибками при дальнейшем расширении либо инициализируй тут.

2021-11-25 23:06 UTC, asrubel commented on ChatBot/src/nix/education/java/hangman/Hangman.java
> +    private String field;
Проверок на null у тебя нет кстати

2021-11-28 10:31 UTC, asrubel approved these changes

2021-11-28 18:58 UTC, merged